print("")
print("<||<||<|| MAD LIBS GENERATOR ||>||>||>")
print("")
print("Hey! Let's get started on your Mad Libs.")
print("Enter in words as specified below...")
print("")
print("")

name = input("Male name: ")
adj1 = input("Adjective 1: ")
adj2 = input("Adjective 2: ")
activity1 = input("Activity 1: ")
activity2 = input("Activity 2: ")
activity3 = input("Activity 3: ")
noun1 = input("Noun 1: ")
noun2 = input("Noun 2: ")
noun4 = input("Noun 4 (plural): ")
place1 = input("Place 1: ")
place2 = input("Place 2: ")

print("")
print(name, " is a ", adj1, noun1, " who lives in ", place1, " and is from a ", adj2, " family. He lives with his ", noun2, " who is the breadwinner of the family. She earns ", noun4, " by ", activity1, " at Walmart. When ", name, "'s ", noun2, " has free time they ", activity2, " together and have fun ", activity3, "in", place2, ".")
print("")
print("The end!")
